### ISSUE TITLE
script/setup not showing full module option

### ISSUE THREAD

**Issue by urbasus** [thindil/tashy#1]
I open the setup/script and see this:

![image](https://user-images.githubusercontent.com/25083765/84592556-da33e800-ae46-11ea-9d29-be4164079ecc.png)

I'm assuming `...` is not an acutal module ;-)

Windows 10, ActiveTcl 8.6.9.

**Comment by thindil** [comment]
Hello here too :) Well, this "..." was expected to mean "and one of the list below" :) Ok, I will remove this dots and do it in normal way.

**Comment by urbasus** [comment]
Ah, now I get it. Normal way sounds good :-)

**Comment by thindil** [comment]
I think now it should be clear :) Thank you for the report. If you think that this can be improved, feel free to reopen this issue or create a new.
