### ISSUE TITLE
script/setup does not find ActiveTcl when guessing macros

### ISSUE THREAD

**Issue by urbasus** [thindil/tashy#2]
Running script/setup I get these "reasonable" values for the macros:

![image](https://user-images.githubusercontent.com/25083765/84592627-6d6d1d80-ae47-11ea-9eb6-b545d15b457a.png)

I have an ActiveTcl distribution install at the default location (C:\ActiveTcl). Several fields are missing, and the paths pointing into Git (for Windows) are wrong.

I'd like setup to check for an ActiveTcl distribution at default location and use that if available.

**Comment by thindil** [comment]
Hello, thank you very much for the report and I'm sorry for the problems. I will look at it tomorrow. Main problem is that I didn't tested yet Tashy against ActiveState Tcl (only MagicSplat)

**Comment by thindil** [comment]
Ok, some investigations are done: 
1. This empty fields are Unix only, so probably the best way to "fix" them will be hide on Windows. As far I know they are not needed on Windows.
2. Detecting path for Tcl. Hmm, that looks a bit "weird" :) The setup script uses `info nameofexecutable` to get full path to the directory where `wish.exe` executable is (line 169 in scripts/setup.tcl). For some reasons it detects that you have `wish.exe` installed in Git directory. Are you sure that there are no `wish.exe` file? Or if it is possible, could you please add below this line that thing:

`puts [info nameofexecutable]`

And write here its output?

**Comment by urbasus** [comment]
Found the problem. It's not you, it's me ;-)

Until now I've only been working with Tcl using Hg and Powershell, which correctly uses the ActiveTcl distro found in my PATH (C:\ActiveTcl). Starting the setup script from the Powershell instance correctly points out the ActiveState distro. All good.

For whatever reason I had installed Git for Windows together with its "common tools", located under Git/mingw. Among the common tools are (to my surprise) tclsh and wish. Git Bash puts those tools on path, and so starting scripts/setup from a Git Bash instance finds the Git/mingw wish instance.

So as far as the setup script goes I'd say it does what it's supposed to.

Unix fields hidden on windows sounds like a good idea from a usability perspective.

**Comment by thindil** [comment]
Okies, then in this issue only this hiding will be done. Good to know that I can sometimes write a piece of code without bugs (of course, these from other issues don't count) :D

**Comment by thindil** [comment]
This one also should be now fixed (from usability perspective). And that same as with previous issue: thank you for the report and if you think that it is not over, feel free to reopen this issue or create a new.

**Comment by urbasus** [comment]
I don't think this is over, and would like to reopen the issue ;-)

On hitting save there is an application error:

```
invalid command name ".grid.x11home-entry"
invalid command name ".grid.x11home-entry"
    while executing
"$g.$w-entry get"
    ("default" arm line 3)
    invoked from within
"switch -regexp $name {
         "(TK|TCL)_(VERSION|RELEASE)" {
            # wasn't displayed, can't have changed
         }
         "EXE" {
        ..."
    (procedure "Save_GUI" line 4)
    invoked from within
"Save_GUI .grid"
    invoked from within
".buttons.save invoke "
    invoked from within
".buttons.save instate !disabled { .buttons.save invoke } "
    invoked from within
".buttons.save instate pressed { .buttons.save state !pressed; .buttons.save instate !disabled { .buttons.save invoke } } "
    (command bound to event)
```

Looks simple enough. Think I can fix it myself. Will open PR in a moment. Please don't hog the (presumably) simple stuff.
